#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    # STOW_FOLDERS="tmux,zsh,vim,bash,git,bin,lvim"
    STOW_FOLDERS="test.sh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
